### ISSUE TITLE
Giving

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#465] opened 2021-10-13 14:53 UTC
When you add a fund to the giving page. save.
Then go back and make a change to the fund.
The giving page doesn't update unless you remove the fund and then add it back.
so then you have to update the fund, then update the fund listing page.

**Comment by nbaxley-uiuc** [comment] 2021-12-03 20:18
This is a caching issue. If you open the page as a logged out person or clear the cache manually the number gets updated. I don't think we need to do any changes here.
Duplicate of #484

**Comment by robgasc** [comment] 2022-01-05 21:02
Can confirm, this is a cache issue. One possible work around might be [inline entity form](https://www.drupal.org/project/inline_entity_form) https://www.drupal.org/project/inline_entity_form; which will allow editing and creation of the giving funds right from the page, like paragraphs currently work. That way you save the fund and listing page together, clearing up the right cache.

A longer alternative might be to consider converting the giving fund into a paragraph, since these elements are never standalone, they would make a great candidate for conversion. That might be a wider change, as we would need to put something together to migrate existing giving funds into paragraphs.

**Comment by nbaxley-uiuc** [comment] 2022-01-07 19:02
I LOVE the idea of making giving funds into a paragraph.  We'll need to think about the implications of a change and there will be some migration as well, but we can take our time to deprecate the current method.  I'm moving this to the backlog milestone but hope to bring it back for v2.5 or so.

**Closed as completed** 2022-01-07 19:03 UTC
Labels: bug
