### ISSUE TITLE
Split video 

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#716] opened 2022-04-19 15:48 UTC
split video - why is the orange going lower on the right of the video?
https://staging.hdfs.illinois.edu/admissions

looks like the youtube video should be taller....but it just fills whitespace instead

so the orange is technically the right height, the youtube video is off

- [ ] padding-bottom of 1.5625rem should be removed.
![image](https://user-images.githubusercontent.com/54747669/164043917-aa465a9a-b1c7-48e8-a423-d11399c0c1e9.png)

**Comment by mwllr** [comment] 2022-04-19 15:51
Robbie added some padding to the bottom of all remote video media.

@robgasc - can you chime in? Do we need this for something?
![image](https://user-images.githubusercontent.com/54747669/164044582-b4850e48-4fe1-439f-a618-3a641094b18d.png)

**Comment by robgasc** [comment] 2022-04-19 16:09
I'd love to, but in this case @trubach added that padding 6 days ago. I'm guessing it has to do with accordions and probably needs to be more specific for the accordion?
![image](https://user-images.githubusercontent.com/62705321/164047811-6ffb9600-b66b-4caf-98a0-341c882a2c4b.png)

**Comment by wrg20** [comment] 2022-04-20 21:34
Yeah I'll qualify it for accordions...thanks @robgasc !

**Comment by trubach** [comment] 2022-04-21 13:52
@wrg20 - I don't think the issue is specific to just accordions. I think it needs to target media embedded through the body (WYSIYWG) field. The specific example I was trying to address is in the screenshot. The image was embedded using the media embed in a body field. You can see the image doesn't have any padding on the right or bottom, and it's left-aligned. I think we could target it with something like 

`.media .field--type-text-long { CSS STUFF }`

What do you think?

![image](https://user-images.githubusercontent.com/56594946/164471713-41c2108c-6fdd-4fd0-b953-87bb84fed1fa.png)

The page where this is happening is at:

https://mcb.web.illinois.edu/academic-programs/undergraduate-programs/mcb-center-advising/career-development

**Comment by wrg20** [comment] 2022-04-21 14:51
OK, let me target that as well @trubach

**Comment by wrg20** [comment] 2022-04-21 15:36
![image](https://user-images.githubusercontent.com/1544079/164497667-ff22b7da-15c7-4c08-b5f7-a4422c34beb3.png)

mp4 embeds need to be either aligned center or enlarged to 100% height.

**Comment by wrg20** [comment] 2022-04-21 19:42
merge #724 should fix the video alignment issue for mp4 above.

**Comment by mwllr** [comment] 2022-05-05 18:28
@trubach - can you test this to see if fixed?

**Comment by trubach** [comment] 2022-05-05 21:02
I'm not seeing the extra padding on the split-video like we did before. See the page:

https://drupal-sandbox.webtheme.illinois.edu/paragraphs/feature-video

Likewise, there's padding around embedded images from the media library. See the bottom of this page:

https://drupal-sandbox.webtheme.illinois.edu/paragraphs/accordion

It looks like it's fixed to me. Feel free to close the issue @mwllr if you're not seeing any issues on the sandbox site.

**Closed as completed** 2022-06-07 20:58 UTC
Labels: bug
