### ISSUE TITLE
New Fund - Layout

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#577] opened 2021-12-03 17:44 UTC
When I create a new fund, the submission display doesn't show in the main content area.
![Screen Shot 2021-12-03 at 11 42 12 AM](https://user-images.githubusercontent.com/54747669/144648449-e286f506-8d44-4252-a096-716f54980180.png)

**Comment by nbaxley-uiuc** [comment] 2021-12-03 20:17
Duplicate of #483

**Closed as completed by nbaxley-uiuc** 2021-12-03 20:17 UTC
