### ISSUE TITLE
Paragraph Permissions

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#177] opened 2021-07-12 21:33 UTC
Please add view permissions for all users for all paragraph content types.

**Comment by trubach** [comment] 2021-07-13 13:37
Hey @mwllr , just for clarification on my part, are you not seeing the paragraphs when logged in under the "Content Manager" role? That's the only other role we have out of the box besides admin.

**Comment by trubach** [comment] 2021-07-13 15:31
The issue is that out of the box, anonymous users can't view paragraphs. Permission has to be granted to view each paragraph type individually.

Solution 1: The Framework has the "Paragraph Type Permissions" module enabled by default. It requires that each paragraph type be given explicit permission to view, which might be a bigger headache than it's worth. If the module isn't enabled, then anyone who can view published content (i.e. anonymous users) can view the content. We can make it so that module isn't enabled by default and that should fix the issue.

Solution 2: Keep the module enabled and update the default configuration so that the anonymous user can view each of those paragraphs. The issue I see with this solution is that if we add any paragraphs in the future, we'll have to remember to update the permissions along with it.

My preferred solution would be to not enable the "Paragraph Type Permissions" by default (solution 1). That should fix the issue and be easier to maintain in the future since we won't have to remember to add the permissions for each new paragraph we create.

@mwllr, @wrg20 , do either of you see an issue with disabling the "Paragraph Type Permissions" module? It also gives the ability to control what paragraphs content managers can use, which might be useful at some point, but I don't see it as a need right now.

**Comment by trubach** [comment] 2021-07-14 13:36
This has been resolved with the [this commit to the profile repository](https://github.com/web-illinois/illinois_framework_profile/pull/11/commits/bf92385ae8d480ca30a8cf531389f9fe199cec64). The "Paragraph Type Permissions" module is no longer enabled by default, which gives all users the ability to view the paragraph if the node is published.

**Closed as completed by trubach** 2021-07-14 13:36 UTC
