### ISSUE TITLE
Documentation for news block

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#523] opened 2021-10-29 20:37 UTC
Create documentation for:

There is concern that the view-page will cause confusion when a site wants to do something different with the /news/ page. In order to have something there for sites with minimal effort, we can leave it there but we need to have a block version of this view available for people to use when they don't want to have the the standard page listing. We can document that the best way to handle this is to disable view-page and then embed the view-block into a Content Page.

**Comment by nbaxley-uiuc** [comment] 2021-12-03 20:27
Duplicate of #425

**Closed as completed by nbaxley-uiuc** 2021-12-03 20:27 UTC
Labels: documentation
