### ISSUE TITLE
http redirects to https

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#640] opened 2022-02-14 17:30 UTC
The cPanel .htaccess rules work independently from the drupal install profile .htaccess file.  This results in an issue where turning on https:// forced redirect within the cPanel interface overwrites the Drupal .httacess file and "whitescreens" the website.  We may need to create a script that adds the forced redirect rules into the .htaccess files after installation / updates.  

See below for Rules for redirection

```
<IfModule mod_rewrite.c>
  RewriteEngine on

  # Set "protossl" to "s" if we were accessed via https://.  This is used later
  # if you enable "www." stripping or enforcement, in order to ensure that
  # you don't bounce between http and https.
  RewriteRule ^ - [E=protossl]
  RewriteCond %{HTTPS} on
  RewriteRule ^ - [E=protossl:s]

  RewriteCond %{HTTPS} off
  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

```

**Comment by jakramer-illinois** [comment] 2022-02-16 15:15
I could not reproduce this on a clean framework install. I installed the framework using the one step composer instructions, visited the site, reviewed the htaccess. Then I toggled Force HTTPS on. No changes were made to .htaccess and the site still functioned correctly.

I'd like to test this further before any changes are made. 

Are you talking about the Force HTTPS toggle from the Domains feature, or are you talking about manually adding rules to the Redirect feature?

The cPanel Force HTTPS feature does not use the .htaccess file, it uses the Apache VHost configuration, so there's no reason it should overwrite the .htaccess file. That's not to say cPanel isn't doing something unexpected, which is why I'd like to test it.

If you mean adding the rules manually to the Redirect feature, that's correct. You should never use the Redirect feature if there is already content in your .htaccess. This could be better documented ;)

**Comment by trubach** [comment] 2022-02-23 21:36
@wrg20 and @jakramer-illinois - I've updated the composer project setup script to enable HTTPS by default after a site is installed using the cPanel API. It was included in the PR at web-illinois/illinois_framework_project#10

Feel free to go ahead and close this ticket if you both are happy with the changes to the composer project.

**Comment by wrg20** [comment] 2022-03-04 16:25
@trubach - were you able to get this working?  I installed a new site and saw the script ran but when I go to http:// it doesn't redirect to https://.  nres.illinois.edu was the site I did.  However I did not note at the time what was echoed out by the script.

**Comment by trubach** [comment] 2022-03-04 17:12
It might take a little bit for the redirect to work, I think. If you go to Domains in your cPanel dashboard, does it show the HTTPS redirect being enabled?

![image](https://user-images.githubusercontent.com/56594946/156810032-996d79f0-4354-4a3c-b45a-4f7ac9610e16.png)

**Comment by trubach** [comment] 2024-04-09 18:16
Closing this issue as this is related to hosting, not the ILFW itself

**Closed as completed by trubach** 2024-04-09 18:16 UTC
